function findGif(ran) {
    switch(ran) {
    case 1:
        return 'https://i.imgur.com/UjYq4If.gif';
    case 2:
        return 'https://i.imgur.com/6YvXWPT.gif';
    case 3:
        return 'https://i.imgur.com/ta2MK9H.gif';
    case 4:
        return 'https://i.imgur.com/G5kYj3p.gif';
    case 5:
        return 'https://i.imgur.com/tPOUxwU.gif';
    case 6:
        return 'https://i.imgur.com/zYzX0Bh.gif';
    case 7:
        return 'https://i.imgur.com/hY9rBFE.gif';
    case 8:
        return 'https://i.imgur.com/A2Lwxdu.gif';
    case 9:
        return 'https://i.imgur.com/BRojOWf.gif';
    case 10:
        return 'https://i.imgur.com/zEcL4Aw.gif';
    case 11:
        return 'https://i.imgur.com/5Y2rLP7.gif';
    case 12:
        return 'https://i.imgur.com/waiptRg.gif';
    case 13:
        return 'https://i.imgur.com/kkfFWH6.gif';
    case 14:
        return 'https://i.imgur.com/9TFyJ8k.gif';
    case 15:
        return 'https://i.imgur.com/PCpK2x8.gif';
    case 16:
        return 'https://i.imgur.com/PxerLBF.gif';
    case 17:
        return 'https://i.imgur.com/XWLfp7U.gif';
    case 18:
        return 'https://i.imgur.com/9bK4kRA.gif';
    case 19:
        return 'https://i.imgur.com/ov0C4kB.gif';
    case 20:
        return 'https://i.imgur.com/wErykSa.gif';
    case 21:
        return 'https://i.imgur.com/YV5VlW7.gif';
    case 22:
        return 'https://i.imgur.com/r0TWK8P.gif';
    case 23:
        return 'https://i.imgur.com/VSO1Tqo.gif';
    case 24:
        return 'https://i.imgur.com/134Y4Sx.gif';
    case 25:
        return 'https://i.imgur.com/ILkMhEi.gif';
    case 26:
        return 'https://i.imgur.com/JhRu30X.gif';
    case 27:
        return 'https://i.imgur.com/sN8VefM.gif';
    case 28:
        return 'https://i.imgur.com/lCHclSL.gif';
    case 29:
        return 'https://i.imgur.com/2vzflFa.gif';
    case 30:
        return 'https://i.imgur.com/Ok9sP84.gif';
    case 31:
        return 'https://i.imgur.com/5Dn8cDd.gif';
    case 32:
        return 'https://i.imgur.com/pULxg9P.gif'
    }
}

module.exports = { findGif };