function findBocchi() {
    const ran = Math.floor(Math.random() * (60 - 1) + 1);

    switch(ran) {
    case 1:
		return 'https://i.imgur.com/wjVM31a.png';
	case 2:
		return 'https://i.imgur.com/kQFrZQ0.png';
	case 3:
		return 'https://i.imgur.com/tqMt5a8.png';
	case 4:
		return 'https://i.imgur.com/CD0VAks.png';
	case 5:
		return 'https://i.imgur.com/IaHenWt.png';
	case 6:
		return 'https://i.imgur.com/ALYHOG4.png';
	case 7:
		return 'https://i.imgur.com/5raB5DM.png';
	case 8:
		return 'https://i.imgur.com/Xk51MqZ.png';
	case 9:
		return 'https://i.imgur.com/c6kSMTU.png';
	case 10:
		return 'https://i.imgur.com/net548m.png';
	case 11:
		return 'https://i.imgur.com/I8QNd2k.png';
	case 12:
		return 'https://i.imgur.com/8Q6kZtt.png';
	case 13:
		return 'https://i.imgur.com/7v3FEF6.png';
	case 14:
		return 'https://i.imgur.com/ACsuL7Z.png';
	case 15:
		return 'https://i.imgur.com/LaWkg0G.png';
	case 16:
		return 'https://i.imgur.com/hDSj2Wm.png';
	case 17:
		return 'https://i.imgur.com/lImdBn0.png';
	case 18:
		return 'https://i.imgur.com/cX7yXoe.png';
	case 19:
		return 'https://i.imgur.com/zYPORni.png';
	case 20:
		return 'https://i.imgur.com/syxFKBx.png';
	case 21:
		return 'https://i.imgur.com/ArfiZYE.png';
	case 22:
		return 'https://i.imgur.com/9RD8dd6.png';
	case 23:
		return 'https://i.imgur.com/2bvBnEa.png';
	case 24:
		return 'https://i.imgur.com/T7EUmdl.png';
	case 25:
		return 'https://i.imgur.com/YoWRxiu.png';
	case 26:
		return 'https://i.imgur.com/xEeQy6U.png';
	case 27:
		return 'https://i.imgur.com/IYHmrwm.png';
	case 28:
		return 'https://i.imgur.com/W0d6QfE.png';
	case 29:
		return 'https://i.imgur.com/NoqHlcG.png';
	case 30:
		return 'https://i.imgur.com/gwkFNsr.png';
	case 31:
		return 'https://i.imgur.com/GyY1JdR.png';
	case 32:
		return 'https://i.imgur.com/yBWaCY1.png';
	case 33:
		return 'https://i.imgur.com/b3Ge2uR.png';
	case 34:
		return 'https://i.imgur.com/ni0sQ9V.png';
	case 35:
		return 'https://i.imgur.com/cmasjAd.png';
	case 36:
		return 'https://i.imgur.com/t1SYgl0.png';
	case 37:
		return 'https://i.imgur.com/5iANaXk.png';
	case 38:
		return 'https://i.imgur.com/gwJ2E0z.png';
	case 39:
		return 'https://i.imgur.com/4eXfMRi.png';
	case 40:
		return 'https://i.imgur.com/ZrhBArG.png';
	case 41:
		return 'https://i.imgur.com/YWtDx6U.png';
	case 42:
		return 'https://i.imgur.com/8SkxT0E.png';
	case 43:
		return 'https://i.imgur.com/36W7Nda.png';
	case 44:
		return 'https://i.imgur.com/7gudfQB.png';
	case 45:
		return 'https://i.imgur.com/4X1PkfW.png';
	case 46:
		return 'https://i.imgur.com/SAb3B6m.png';
	case 47:
		return 'https://i.imgur.com/RvZYXBc.png';
	case 48:
		return 'https://i.imgur.com/jTSqEhk.png';
	case 49:
		return 'https://i.imgur.com/b4RUZfF.png';
	case 50:
		return 'https://i.imgur.com/WCTibMH.png';
	case 51:
		return 'https://i.imgur.com/AFoUDV7.png';
	case 52:
		return 'https://i.imgur.com/QTHkCda.png';
	case 53:
		return 'https://i.imgur.com/H3CP0KZ.png';
	case 54:
		return 'https://i.imgur.com/GUigsnS.png';
	case 55:
		return 'https://i.imgur.com/20BK5ui.png';
	case 56:
		return 'https://i.imgur.com/AtxZpsi.png';
	case 57:
		return 'https://i.imgur.com/LnXHJi4.png';
	case 58:
		return 'https://i.imgur.com/x2m7OBX.png';
	case 59:
		return 'https://i.imgur.com/yaH8QQL.png';
	case 60:
		return 'https://i.imgur.com/jab2xES.png';
    }
}

module.exports = { findBocchi };